Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PonfeLibrary.Models;

namespace PonfeLibrary.Controllers
{
    public class AuthorController : Controller
    {
        LibraryContext db;

        public AuthorController(LibraryContext lib)
        {
            db = lib;
        }
        [HttpGet]
        public IActionResult Show()
        {
            List<Author> authors = db.Author.OrderBy(a => a.Name).ToList();
            ViewBag.Authors = authors;
            return View("Views/Author/Author.cshtml");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var au = await db.Author.FindAsync(id);
            if (au == null)
            {
                return NotFound();
            }
            return View("Edit",au);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Nationality")] Author author )
        {
            if (id != author.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    db.Update(author);
                    await db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
                return RedirectToAction(nameof(Show));
            }
            return View(author);
        }
        [HttpGet]
        public async Task<IActionResult> Add()
        {
            return View("Add");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add([Bind("Name, Nationality")] Author au)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Add(au);
                    await db.SaveChangesAsync();
                    return RedirectToAction(nameof(Show));
                }
            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Unable to save changes. " + "Please try again.");
            }
            return View(au);
        }
        
        public async Task<IActionResult> Delete (int? id)
        {
            Author au = await db.Author.FindAsync(id);
            try
            {
                if(au == null)
                {
                    return RedirectToAction(nameof(Show));

                }
                db.Author.Remove(au);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Show));

            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Unable to save changes. " + "Please try again.");
            }
            return RedirectToAction(nameof(Show));
        }

    }
}

Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PonfeLibrary.Models;

namespace PonfeLibrary.Controllers
{
    public class BookController : Controller
    {
        LibraryContext db;
        public BookController (LibraryContext lib)
        {
            db = lib;
        }
        [HttpGet]
        public IActionResult Show()
        {
            List<Book> books = db.Book.OrderBy(b => b.Title).ToList();
            ViewBag.Books = books;
            return View("Views/Book/Book.cshtml");
        }
        protected Book complementInformation (int? id)
        {
            if (id == null)
            {
                return null;
            }

            var book = db.Book.
                Include(b => b.BookAuth).
                    ThenInclude(a => a.Auth).
                Include(b => b.BookGen).
                    ThenInclude(g => g.Gen).
                Include(b => b.Pub).
                Where(b => b.Id == id).
                FirstOrDefault();
            if (book == null)
            {
                return null;
            }
            return book;
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            Book book = complementInformation(id);
            if (book == null) return NotFound();
            List<Genre> genres = db.Genre.OrderBy(g => g.Name).ToList();
            List<Author> authors = db.Author.OrderBy(a => a.Name).ToList();
            List<Publisher> publishers = db.Publisher.OrderBy(p => p.Name).ToList();
            ViewBag.Authors = authors;
            ViewBag.Genres = genres;
            ViewBag.Publishers = publishers;
            return View("Edit", book);
        }
        [HttpGet]
        public IActionResult Details(int? id)
        {

            Book book = complementInformation(id);
            if(book == null)return NotFound();
            return new ObjectResult(book);
        }
        [HttpGet]
        public async Task<IActionResult> Add()
        {
            return View("Add");
        }
        /*[HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add([Bind("Title, Subtitle, Isbn, Authors, Pub, Genre")] Book book)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Add(book);
                    await db.SaveChangesAsync();
                    return RedirectToAction(nameof(Show));
                }
            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Unable to save changes. " + "Please try again.");
            }
            return View(nameof(Show));
        }*/
        [HttpDelete]
        public async Task<IActionResult> Delete(int? id)
        {
            Book book = await db.Book.FindAsync(id);
            try
            {
                if (book == null)
                {
                    return RedirectToAction(nameof(Show));

                }
                db.Book.Remove(book);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Show));

            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Unable to save changes. " + "Please try again.");
            }
            return RedirectToAction(nameof(Show));
        }
    }
   
}

Controllers/GenreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PonfeLibrary.Models;

namespace PonfeLibrary.Controllers
{
    public class GenreController : Controller
    {
        LibraryContext db;
        public GenreController(LibraryContext lib)
        {
            db = lib;
        }
        [HttpGet]
        public IActionResult Show()
        {
            List<Genre> genres = db.Genre.OrderBy(g => g.Name).ToList();
            ViewBag.Genres = genres;
            return View("Views/Genre/Genre.cshtml");
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gen = await db.Genre.FindAsync(id);
            if (gen == null)
            {
                return NotFound();
            }
            return View(gen);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Nationality")] Genre genre)
        {
            if (id != genre.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    db.Update(genre);
                    await db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
                return RedirectToAction(nameof(Show));
            }
            return View(genre);
        }
        [HttpGet]
        public async Task<IActionResult> Add()
        {
            return View("Add");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add([Bind("Name, Description")] Genre gen)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Add(gen);
                    await db.SaveChangesAsync();
                    return RedirectToAction(nameof(Show));
                }
            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Unable to save changes. " + "Please try again.");
            }
            return View(nameof(Show));
        }
        
        public async Task<IActionResult> Delete(int? id)
        {
            Genre gen = await db.Genre.FindAsync(id);
            try
            {
                if (gen == null)
                {
                    return RedirectToAction(nameof(Show));

                }
                db.Genre.Remove(gen);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Show));

            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Unable to save changes. " + "Please try again.");
            }
            return RedirectToAction(nameof(Show));
        }
    }
}

Controllers/PublisherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PonfeLibrary.Models;

namespace PonfeLibrary.Controllers
{
    public class PublisherController : Controller
    {
        LibraryContext db;
        public PublisherController(LibraryContext lib)
        {
            db = lib;
        }
        [HttpGet]
        public IActionResult Show()
        {
            List<Publisher> publishers = db.Publisher.OrderBy(p => p.Name).ToList();
            ViewBag.Publishers = publishers;
            return View("Views/Publisher/Publisher.cshtml");
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pub = await db.Publisher.FindAsync(id);
            if (pub == null)
            {
                return NotFound();
            }
            return View(pub);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Nationality")] Publisher publisher)
        {
            if (id != publisher.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    db.Update(publisher);
                    await db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
                return RedirectToAction(nameof(Show));
            }
            return View(publisher);
        }
        [HttpGet]
        public async Task<IActionResult> Add()
        {
            return View("Add");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add([Bind("Name")] Publisher pub)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Add(pub);
                    await db.SaveChangesAsync();
                    return RedirectToAction(nameof(Show));
                }
            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Unable to save changes. " + "Please try again.");
            }
            return View(nameof(Show));
        }
        
        public async Task<IActionResult> Delete(int? id)
        {
            Publisher pub = await db.Publisher.FindAsync(id);
            try
            {
                if (pub == null)
                {
                    return RedirectToAction(nameof(Show));

                }
                db.Publisher.Remove(pub);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Show));

            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Unable to save changes. " + "Please try again.");
            }
            return RedirectToAction(nameof(Show));
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>PonfeLibrary</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Mandali&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/style/normalize.css" />
    <link rel="stylesheet" href="~/style/style.css" />
    <link rel="stylesheet" href="~/style/containers.css" />
    <link rel="stylesheet" href="~/style/modal.css" />
</head>
<body>
    <header>
        <nav class="nav-container">
            <div class="title-container">
                <a class="" asp-area="" asp-controller="Book" asp-action="Show">PonfeLibrary</a>
            </div>
            <div class="items-container">
                <ul class="">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Book" asp-action="Show">Books</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Genre" asp-action="Show">Genres</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Publisher" asp-action="Show">Publishers</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Author" asp-action="Show">Authors</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="">
            @RenderBody()
        </main>
        <div class="add-button">
            <a onclick="toggleModal('add-modal')">
                <span id="add-icon" class="material-icons">
                    add
                </span>
            </a>
        </div>
        <div id="add-modal" class="modal">
            <div class="modal-content">
                <span>
                    Choose what do you want to add
                </span>
                <div >
                    <a class="add-item" asp-controller="Book" asp-action="Add" >
                        Book            
                    </a>                
                    <a class="add-item" asp-controller="Genre" asp-action="Add" >
                        Genre           
                    </a>                
                    <a class="add-item" asp-controller="Publisher" asp-action="Add" >
                        Publisher       
                    </a>                
                    <a class="add-item" asp-controller="Author" asp-action="Add" >
                        Author
                    </a>
                </div>
                <div class="button-holder">
                    <a onclick="toggleModal('add-modal')">Cancel</a>
                </div>
            </div>
        </div>
    </div>
    <footer>
        <div class="container">
            2020   &copy;   Enzo Ponferrada
        </div>
    </footer>
    <script src="~/scripts/site.js"></script>
   <!--<script src="~/js/site.js" asp-append-version="true"></script>-->
    @RenderSection("Scripts", required: false)
</body>
</html>